services:
  middleware-payment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-${APP_ENV}
    entrypoint: php artisan octane:frankenphp --max-requests=5
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - .:/app
    networks:
      - middleware-payment # Use the network defined below

networks:
  middleware-payment:
    driver: bridge # Use the bridge driver (default for container-to-container communication)
